### ISSUE TITLE
Hacktober-fest opportunity 

### ISSUE THREAD

**Issue by tanwanimohit** [tanwanimohit/visualize-algorithms#3]
**What can you do?**
Choose any from below..

- Update the README.md file add description and clone information.
- Add New Sorting Algorithm
- Improve the UI / Make it more user friendly and responsive.

Every PR will be Appreciated.
Star the PR and Share it with your Friends.

Thankyou.

**Comment by ps011** [comment]
I'll improve the UI a bit and raise a PR.

**Comment by ps011** [comment]
Raised a PR https://github.com/tanwanimohit/visualize-algorithms/pull/5
